language: "node_js"
node_js:
  - "v5"
  - "v4"
  - "0.12"
  - "0.10"

before_install:
 - "npm install istanbul -g"
 - "npm install coveralls -g"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
